=== Ghada-Emad1/ITI-Laps/XML/day3/library.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Library">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="location" type="xs:string" />
                <xs:element name="description" type="xs:string" />
                <xs:element name="librarian" type="xs:string" />
                <xs:element name="book">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string" />
                            <xs:element name="ISBN" type="xs:string" minOccurs="0" />
                            <xs:element name="Author" type="xs:string" />
                            <xs:element name="preface" type="xs:string" minOccurs="0" />
                            <xs:element name="part">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="title">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="chapter">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="title"
                                                                    type="xs:string" />
                                                                <xs:element name="summary"
                                                                    type="xs:string" />
                                                                <xs:element name="section">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element
                                                                                name="content">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>
                                                                                        <xs:element
                                                                                            name="paragraph"
                                                                                            type="xs:string" />
                                                                                    </xs:sequence>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                            <xs:attribute name="chapter"
                                                                type="xs:string" />
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="language" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Ghada-Emad1/ITI-Laps/XML/day3/library.xml
<?xml version="1.0"?>
<Library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="library.xsd">
  <location>Cairo</location>
  <description>It is an amazing Library</description>
  <librarian>Ghada Emad</librarian>
  <book language="arabic">
    <title>Great Book</title>
    <ISBN />
    <Author>Naguib Mahfouz</Author>
    <preface />
    <part>
      <title>
        <chapter chapter="1">
          <title>Chapter1</title>
          <summary>It is a new chapter</summary>
          <section>
            <content>
              <paragraph>
                <![CDATA[
                Filled with breathtaking landscapes, unexpected challenges      
                ///\\\
                _______
                \\\///
                It's a story that captivates and inspires.
                ]]>
              </paragraph>
            </content>
          </section>
        </chapter>
      </title>
    </part>
  </book>
</Library>
