=== Ghada-Emad1/ITI-Laps/XML/day2/lap2.dtd
<!ELEMENT Library (location,description,librarian,book)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT librarian (#PCDATA)>
<!ELEMENT book (title,ISBN,Author,preface,part)>
<!ATTLIST book language CDATA #REQUIRED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT ISBN EMPTY>
<!ELEMENT Author (#PCDATA)>
<!ELEMENT preface EMPTY>
<!ELEMENT part (BookTitle)>
<!ELEMENT BookTitle (chapter+)>
<!ELEMENT chapter (title, summary, section)>
<!ATTLIST chapter id ID #REQUIRED>
<!ELEMENT summary (#PCDATA)>
<!ELEMENT section (content+)>
<!ELEMENT content (paragraph+)>
<!ELEMENT paragraph (#PCDATA)>

=== Ghada-Emad1/ITI-Laps/XML/day2/lap2.xml
<?xml version="1.0"?>
<!DOCTYPE Library SYSTEM "lap2.dtd">


<Library>
   <location>Cairo</location>
   <description>It is an amazing Library</description>
   <librarian>Ghada Emad</librarian>
   <book language="arabic">
      <title>Great Book</title>
      <ISBN />
      <Author>Naguib Mahfouz</Author>
      <preface />
      <part>
         <BookTitle>
            <chapter id="ch1">
               <title>Chapter1</title>
               <summary>it is new chapter</summary>
               <section>
                  <content>
                     <paragraph>
                  <![CDATA[
        Filled with breathtaking landscapes, unexpected challenges      
        ///\\\
        _______
        \\\///
        It's a story that captivates and inspires,
         ]]>
                 </paragraph>

                  </content>
               </section>
            </chapter>
         </BookTitle>
      </part>
   </book>
</Library>
